In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("country_vaccination_stats.csv")

In [3]:
df.head(10)

     country        date  daily_vaccinations   vaccines
0  Argentina  12/29/2020                 NaN  Sputnik V
1  Argentina  12/30/2020             15656.0  Sputnik V
2  Argentina  12/31/2020             15656.0  Sputnik V
3  Argentina    1/1/2021             11070.0  Sputnik V
4  Argentina    1/2/2021              8776.0  Sputnik V
5  Argentina    1/3/2021              7400.0  Sputnik V
6  Argentina    1/4/2021              6483.0  Sputnik V
7  Argentina    1/5/2021              7984.0  Sputnik V
8  Argentina    1/6/2021              8173.0  Sputnik V
9  Argentina    1/7/2021              8363.0  Sputnik V

In [4]:
df.groupby('country')['daily_vaccinations'].apply(lambda x: x.isna().sum())

country
Argentina               1
Austria                 1
Bahrain                 1
Belgium                 1
Brazil                  1
Bulgaria                1
Canada                  1
Chile                   1
China                   1
Costa Rica              1
Croatia                 1
Cyprus                  1
Czechia                 1
Denmark                 1
Ecuador                 1
England                 1
Estonia                 1
Finland                 1
France                  1
Germany                 1
Gibraltar               1
Greece                  1
Hungary                 1
Iceland                 1
India                   1
Indonesia               1
Ireland                 1
Isle of Man             1
Israel                  1
Italy                   1
Kuwait                  1
Latvia                  1
Lithuania               1
Luxembourg              1
Malta                   1
Mexico                  1
Netherlands             1
Northern Ireland        1
Norway                  1
Oman                    1
Panama                  1
Poland                  1
Portugal                1
Romania                 1
Russia                  1
Saudi Arabia            1
Scotland                1
Serbia                  1
Seychelles              1
Singapore               1
Slovakia                1
Slovenia                1
Spain                   1
Sweden                  1
Switzerland             1
Turkey                  1
United Arab Emirates    1
United Kingdom          1
United States           1
Wales                   1
Name: daily_vaccinations, dtype: int64

## Answer to question 4

In [5]:
# Create a dictionary to store minimum daily vaccination number for each country
min_daily_vaccinations = {}

# Iterate over each country in the dataset
for country in df["country"].unique():
    
    # Get the minimum daily vaccination number for the country
    min_daily_vacc = df[df["country"] == country]["daily_vaccinations"].min()
    
    # Store the minimum daily vaccination number in the dictionary
    min_daily_vaccinations[country] = min_daily_vacc

# Fill missing values in daily_vaccinations column with the minimum daily vaccination number of relevant countries
df["daily_vaccinations"] = df.groupby("country")["daily_vaccinations"].apply(lambda x: x.fillna(min_daily_vaccinations[x.name] if not np.isnan(min_daily_vaccinations[x.name]) else 0))

In [6]:
df.head(20)

      country        date  daily_vaccinations   vaccines
0   Argentina  12/29/2020              6483.0  Sputnik V
1   Argentina  12/30/2020             15656.0  Sputnik V
2   Argentina  12/31/2020             15656.0  Sputnik V
3   Argentina    1/1/2021             11070.0  Sputnik V
4   Argentina    1/2/2021              8776.0  Sputnik V
5   Argentina    1/3/2021              7400.0  Sputnik V
6   Argentina    1/4/2021              6483.0  Sputnik V
7   Argentina    1/5/2021              7984.0  Sputnik V
8   Argentina    1/6/2021              8173.0  Sputnik V
9   Argentina    1/7/2021              8363.0  Sputnik V
10  Argentina    1/8/2021             10519.0  Sputnik V
11  Argentina    1/9/2021             11942.0  Sputnik V
12  Argentina   1/10/2021             13365.0  Sputnik V
13  Argentina   1/11/2021             14788.0  Sputnik V
14  Argentina   1/12/2021             14056.0  Sputnik V
15  Argentina   1/13/2021             13323.0  Sputnik V
16  Argentina   1/14/2021             13320.0  Sputnik V
17  Argentina   1/15/2021             13317.0  Sputnik V
18  Argentina   1/16/2021             12971.0  Sputnik V
19  Argentina   1/17/2021             12624.0  Sputnik V

## Answer to question 5

In [9]:
# Calculate the median daily vaccinations per country
median_daily_vaccinations = df.groupby("country")["daily_vaccinations"].median()

# Sort the countries by median daily vaccinations in descending order
sorted_countries = median_daily_vaccinations.sort_values(ascending=False)

# Get the top 3 countries with highest median daily vaccinations
top_3_countries = sorted_countries.head(3)

# Print the top 3 countries
print(top_3_countries)

country
United States    378253.0
China            276786.0
India            173922.0
Name: daily_vaccinations, dtype: float64

## Answer to question 6

In [8]:
# filter the dataframe to only include rows where date is 1/6/2021
df_filtered = df[df["date"] == "1/6/2021"]

# sum the daily_vaccinations column for the filtered dataframe
total_vaccinations = df_filtered["daily_vaccinations"].sum()

print("Total vaccinations on 1/6/2021:", total_vaccinations)

Total vaccinations on 1/6/2021: 1485255.0